"""Extract utterance embeddings to NPZ; default is whole-utterance evaluation."""
import argparse
import json
from pathlib import Path
import numpy as np
import torch
import torch.nn.functional as F
from Dataset.data import read_manifest, load_audio
from Features.frontend import build_extractor
from Model.system import SpeakerSystem


def load_system(checkpoint_path, device):
    checkpoint = torch.load(checkpoint_path, map_location='cpu', weights_only=True)
    if checkpoint.get('format_version') != 1:
        raise ValueError('Expected a checkpoint generated by Model.train, not a legacy embedding_model.ckpt')
    cfg = checkpoint['config']
    model = SpeakerSystem(cfg).to(device)
    model.load_state_dict(checkpoint['model'], strict=True)
    model.eval()
    return model, build_extractor(cfg['feature']), cfg


def chunks(wav, seconds=None, sample_rate=16000):
    if seconds is None:
        # ECAPA reflection padding needs several time frames for very short clips.
        yield F.pad(wav, (0, max(0, 1600 - wav.numel())))
        return
    size = round(seconds * sample_rate)
    if size < 1600:
        raise ValueError('chunk_seconds must be at least 0.1')
    if wav.numel() <= size:
        yield F.pad(wav, (0, size - wav.numel()))
        return
    full = wav.numel() // size
    for i in range(full):
        yield wav[i * size:(i + 1) * size]
    if wav.numel() - full * size >= 2 * sample_rate:
        yield wav[-size:]


@torch.inference_mode()
def embed(wav, model, extractor, device, chunk_seconds=None):
    embeddings = [model(extractor(chunk).unsqueeze(0).to(device)).squeeze(0)
                  for chunk in chunks(wav, chunk_seconds)]
    averaged = torch.stack(embeddings).mean(0)
    if not torch.isfinite(averaged).all() or averaged.norm() < 1e-12:
        raise ValueError('Invalid or zero embedding')
    return F.normalize(averaged, dim=0).cpu().numpy()


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--checkpoint', required=True)
    p.add_argument('--csv', required=True)
    p.add_argument('--output', required=True, help='.npz file')
    p.add_argument('--device', default='cuda' if torch.cuda.is_available() else 'cpu')
    p.add_argument('--chunk-seconds', type=float, help='Optional nonoverlapping chunks; tail >=2 s adds end-aligned chunk')
    args = p.parse_args()
    if not args.output.endswith('.npz'):
        raise ValueError('--output must end in .npz')
    device = torch.device(args.device)
    model, extractor, cfg = load_system(args.checkpoint, device)
    rows = read_manifest(args.csv)
    vectors = []
    for i, row in enumerate(rows):
        vectors.append(embed(load_audio(row), model, extractor, device, args.chunk_seconds))
        if i % 100 == 0:
            print(f'Extracted {i + 1}/{len(rows)}', flush=True)
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(output, ids=np.asarray([r['ID'] for r in rows]), embeddings=np.stack(vectors))
    output.with_suffix('.json').write_text(json.dumps({'checkpoint': str(Path(args.checkpoint).resolve()),
        'csv': str(Path(args.csv).resolve()), 'feature': cfg['feature'], 'utterances': len(rows),
        'chunk_seconds': args.chunk_seconds, 'aggregation': 'raw embedding mean, then L2 normalization'}, indent=2))


if __name__ == '__main__':
    main()
